### ISSUE TITLE
9.1 poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [asienik/zadanie_9_1_funkcje#1]
- [x] zwroc uwage, ze teraz Twoj kod dziala w ten sposob, ze wyswietla 4 wyniki dzialania funkcji, a wlasciwie powinien wyswietlac go tylko raz kiedy faktycznie chcesz to zrobic w ostatniej linii `console.log(getTriangleArea(10, 6))`. 
Intencja kodu w liniach 9-11 jest to, ze przypisujesz do zmiennej to, co zwraca wywolanie funkcji `getTriangleArea`, a jak wyswietlilabys sobie ktoras z tych zmiennych `console.log(triangle1Area);`, to co bys otrzymala?
Dzieje sie tak dlatego, ze Twoja funkcja za kazdym jej wywolaniem nie zwraca wyniku przez return, tylko wyswietla go w konsoli.
Zamien wiec w deklaracji funkcji console.log na return
- [x] wyswietl w konsoli zawartosc zmiennych `triangle1Area`, `triangle2Area`, `triangle3Area`
- [x] usun niepotrzebne komentarze z pliku js
- [x] popraw wciecia w js. Po deklaracji zmiennych na poczatku, kolejna linia powinna sie zaczynac bez wciecia poniewaz nie znajduje sie wewnatrz innego kodu.

**Comment by asienik** [comment]
W takim razie ja chyba nie rozumiem tego polecenia:
Zrób trzy zmienne, które będą przechowywały pole trójkąta, za każdym razem przekazując różne liczby w parametrze. Podpowiedź: var triangle1Area = getTriangleArea(10, 15);  To co to oznacza, ze mają przekazywać rózne liczby w parametrze?

**Comment by asienik** [comment]
czy w konsoli ma to tak wygladać?:
triangle1Area (10, 15)
triangle2Area (2, 3) 
triangle3Area (5, 6)
30

**Comment by michal-bootcamp** [comment]
1. Zostalo jeszcze poprawienie wciec wewnatrz deklaracji funkcji.
Niech nawiasy zamykajace sa wciete na tej samej wysokosci, co komenda, ktora zawiera nawias otwierajacy. Natomiast to, co wewnatrz tych nawiasow powinno miec dodatkowe wciecie.
2. Zamiast nawiasow w returnie `return(a * h / 2);`, napisz po prostu `return a * h / 2;`
